apiVersion: v1
kind: ConfigMap
metadata:
  name: playlist-config
  namespace: giovanamachado
data:
  # Dataset configuration - update this to switch between ds1 and ds2
  DATASET_URL: "/home/datasets/spotify/2023_spotify_ds2.csv"
  DATASET_NAME: "ds2"
  MODEL_FILENAME: "rules_ds2.pkl"
  
  # Model generation parameters
  MIN_SUPPORT: "0.05"
  MIN_CONFIDENCE: "0.5"
  MIN_LIFT: "1.5"
  
  # API configuration
  API_PORT: "50013"
  API_VERSION: "2.0.0"
