apiVersion: v1
kind: ConfigMap
metadata:
  name: playlist-config
  namespace: giovanamachado
data:
  # Dataset configuration - update this to switch between ds1 and ds2
  DATASET_URL: "/home/datasets/spotify/2023_spotify_ds1.csv"
  DATASET_NAME: "ds1"
  MODEL_FILENAME: "rules_ds1.pkl"
  
  # Model generation parameters
  MIN_SUPPORT: "0.01"
  MIN_CONFIDENCE: "0.3"
  MIN_LIFT: "1.0"
  
  # API configuration
  API_PORT: "50013"
  API_VERSION: "1.0.0"
