apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-svc
  namespace: giovanamachado
spec:
  type: ClusterIP
  selector:
    app: giovanamachado-playlist-recommender
  ports:
  - protocol: TCP
    port: 50013      # Cluster IP port to use when calling the service
    targetPort: 50013  # Container port where Flask listens (API_PORT)
    name: http
